export const display_mapping = {
    "+":"#",
    "&":"b",
    "5":"Fifth",
    "6":"Sixth",
    "7":"Seventh",
    "9":"Ninth",
    "Q":"Eleventh",
    "U":"Thirteenth",
    "S":"Seventh flat ninth",
    "s":"Seventh sharp ninth",
    "t":"Seventh sharp eleventh",
    "p":"Seventh flat fifth",
    "q":"Seventh sharp fifth",
    "m":"Seventh flat ninth",
    "r":"Ninth sharp eleventh",
    "T":"Ninth flat fifth",
    "n":"Ninth sharp fifth",
    "2":"Ninth sharp thirteenth",
    "M":"Seventh sharp fifth sharp ninth",
    "O":"Seventh flat fifth sharp ninth",
    "N":"Seventh sharp ninth sharp eleventh",
    "P":"Seventh flat ninth sharp eleventh",
    "L":"Seventh flat ninth flat fifth",
    "J":"Seventh flat ninth sharp fifth",
    "K":"Seventh flat ninth sharp ninth",
    "I":"Seventh flat ninth flat thirteenth",
    "?":"Altered seventh",
    "l":"Thirteenth sharp eleventh",
    "u":"Thirteenth flat ninth",
    "o":"Thirteenth sharp ninth",
    "a":"Minor",
    "b":"Minor seventh",
    "h":"Minor ninth",
    "i":"Minor eleventh",
    "W":"Half diminished seventh",
    "Y":"Half diminished eleventh",
    "X":"Half diminished ninth",
    "f":"Minor major seventh",
    "g":"Minor major ninth",
    "8":"Diminished seventh",
    ">":"Diminished triad",
    "j":"Minor sixth",
    "Z":"Minor sixth ninth",
    "R":"Minor flat sixth",
    "3":"Minor thirteenth",
    "V":"Minor sharp fifth",
    "=":"Added ninth",
    "k":"Sixth ninth",
    "c":"Delta seventh",
    "d":"Delta ninth",
    "x":"Delta seventh sharp eleventh",
    "z":"Delta seventh sharp fifth",
    "y":"Delta ninth sharp eleventh",
    "1":"Delta seventh flat fifth",
    "e":"Delta thirteenth",
    "0":"Seventh sharp ninth flat thirteenth",
    "%":"Minor added ninth",
    "4":"Suspended",
    "v":"Suspended seventh flat ninth",
    "H":"Suspended seventh added thirteenth",
    "]":"Suspended ninth",
    "<":"Suspended thirteenth",
    "w":"Suspended seventh flat thirteenth",
    "[":"Suspended seventh",
    "@":"Augmented"
};
export const display_mapping = {
    "+":"#",
    "&":"b",
    "5":"Fifth",
    "6":"Sixth",
    "7":"Seventh",
    "9":"Ninth",
    "Q":"Eleventh",
    "U":"Thirteenth",
    "S":"Seventh flat ninth",
    "s":"Seventh sharp ninth",
    "t":"Seventh sharp eleventh",
    "p":"Seventh flat fifth",
    "q":"Seventh sharp fifth",
    "m":"Seventh flat ninth",
    "r":"Ninth sharp eleventh",
    "T":"Ninth flat fifth",
    "n":"Ninth sharp fifth",
    "2":"Ninth sharp thirteenth",
    "M":"Seventh sharp fifth sharp ninth",
    "O":"Seventh flat fifth sharp ninth",
    "N":"Seventh sharp ninth sharp eleventh",
    "P":"Seventh flat ninth sharp eleventh",
    "L":"Seventh flat ninth flat fifth",
    "J":"Seventh flat ninth sharp fifth",
    "K":"Seventh flat ninth sharp ninth",
    "I":"Seventh flat ninth flat thirteenth",
    "?":"Altered seventh",
    "l":"Thirteenth sharp eleventh",
    "u":"Thirteenth flat ninth",
    "o":"Thirteenth sharp ninth",
    "a":"Minor",
    "b":"Minor seventh",
    "h":"Minor ninth",
    "i":"Minor eleventh",
    "W":"Half diminished seventh",
    "Y":"Half diminished eleventh",
    "X":"Half diminished ninth",
    "f":"Minor major seventh",
    "g":"Minor major ninth",
    "8":"Diminished seventh",
    ">":"Diminished triad",
    "j":"Minor sixth",
    "Z":"Minor sixth ninth",
    "R":"Minor flat sixth",
    "3":"Minor thirteenth",
    "V":"Minor sharp fifth",
    "=":"Added ninth",
    "k":"Sixth ninth",
    "c":"Delta seventh",
    "d":"Delta ninth",
    "x":"Delta seventh sharp eleventh",
    "z":"Delta seventh sharp fifth",
    "y":"Delta ninth sharp eleventh",
    "1":"Delta seventh flat fifth",
    "e":"Delta thirteenth",
    "0":"Seventh sharp ninth flat thirteenth",
    "%":"Minor added ninth",
    "4":"Suspended",
    "v":"Suspended seventh flat ninth",
    "H":"Suspended seventh added thirteenth",
    "]":"Suspended ninth",
    "<":"Suspended thirteenth",
    "w":"Suspended seventh flat thirteenth",
    "[":"Suspended seventh",
    "@":"Augmented"
};

export const send_mapping = {
    "+":"#",
    "&":"b",
    "5":"Fifth",
    "6":"Sixth",
    "7":"Seventh",
    "9":"Ninth",
    "Q":"Eleventh",
    "U":"Thirteenth",
    "S":"Seventh flat ninth",
    "s":"Seventh sharp ninth",
    "t":"Seventh sharp eleventh",
    "p":"Seventh flat fifth",
    "q":"Seventh sharp fifth",
    "m":"Seventh flat ninth",
    "r":"Ninth sharp eleventh",
    "T":"Ninth flat fifth",
    "n":"Ninth sharp fifth",
    "2":"Ninth sharp thirteenth",
    "M":"Seventh sharp fifth sharp ninth",
    "O":"Seventh flat fifth sharp ninth",
    "N":"Seventh sharp ninth sharp eleventh",
    "P":"Seventh flat ninth sharp eleventh",
    "L":"Seventh flat ninth flat fifth",
    "J":"Seventh flat ninth sharp fifth",
    "K":"Seventh flat ninth sharp ninth",
    "I":"Seventh flat ninth flat thirteenth",
    "F":"Altered seventh",
    "l":"Thirteenth sharp eleventh",
    "u":"Thirteenth flat ninth",
    "o":"Thirteenth sharp ninth",
    "a":"Minor",
    "b":"Minor seventh",
    "h":"Minor ninth",
    "i":"Minor eleventh",
    "W":"Half diminished seventh",
    "Y":"Half diminished eleventh",
    "X":"Half diminished ninth",
    "f":"Minor major seventh",
    "g":"Minor major ninth",
    "8":"Diminished seventh",
    "E":"Diminished triad",
    "j":"Minor sixth",
    "Z":"Minor sixth ninth",
    "R":"Minor flat sixth",
    "3":"Minor thirteenth",
    "V":"Minor sharp fifth",
    "D":"Added ninth",
    "k":"Sixth ninth",
    "c":"Delta seventh",
    "d":"Delta ninth",
    "x":"Delta seventh sharp eleventh",
    "z":"Delta seventh sharp fifth",
    "y":"Delta ninth sharp eleventh",
    "1":"Delta seventh flat fifth",
    "e":"Delta thirteenth",
    "0":"Seventh sharp ninth flat thirteenth",
    "%":"Minor added ninth",
    "4":"Suspended",
    "v":"Suspended seventh flat ninth",
    "H":"Suspended seventh added thirteenth",
    "B":"Suspended ninth",
    "C":"Suspended thirteenth",
    "w":"Suspended seventh flat thirteenth",
    "A":"Suspended seventh",
    "G":"Augmented"    
} 